export interface DataSourceConfig {
  id: string;
  name: string;
  description: string;
  category: "natural" | "transport" | "intelligence" | "environment" | "economic";
  endpoint: string;
  interval: string;
  requiresKey: boolean;
  keyEnvVar?: string;
  status: "active" | "available" | "requires-key";
  layerId?: string; // maps to useLayerStore key
  recordType: string;
  provider: string;
  docs?: string;
}

export const DATA_SOURCE_CATALOG: DataSourceConfig[] = [
  // ── Active (free, no key) ──────────────────────
  {
    id: "usgs-earthquakes",
    name: "USGS Earthquakes",
    description: "Real-time seismic activity worldwide. Updated every 5 minutes from USGS GeoJSON feed.",
    category: "natural",
    endpoint: "earthquake.usgs.gov",
    interval: "5 min",
    requiresKey: false,
    status: "active",
    layerId: "earthquakes",
    recordType: "Seismic events",
    provider: "U.S. Geological Survey",
    docs: "https://earthquake.usgs.gov/fdsnws/event/1/",
  },
  {
    id: "nasa-eonet",
    name: "NASA EONET Disasters",
    description: "Active natural disaster events — wildfires, storms, volcanic eruptions, floods — via NASA Earth Observatory.",
    category: "natural",
    endpoint: "eonet.gsfc.nasa.gov",
    interval: "15 min",
    requiresKey: false,
    status: "active",
    layerId: "disasters",
    recordType: "Active events",
    provider: "NASA EONET",
    docs: "https://eonet.gsfc.nasa.gov/docs/v3",
  },
  {
    id: "opensky-flights",
    name: "OpenSky Flights",
    description: "Live aircraft tracking from the OpenSky Network. Shows airborne flights with callsign, altitude, and velocity.",
    category: "transport",
    endpoint: "opensky-network.org",
    interval: "30 sec",
    requiresKey: false,
    status: "active",
    layerId: "flights",
    recordType: "Aircraft states",
    provider: "OpenSky Network",
    docs: "https://openskynetwork.github.io/opensky-api/",
  },
  {
    id: "gdelt-news",
    name: "GDELT News Events",
    description: "Geolocated news events related to supply chain, trade, and shipping disruptions from the GDELT Project.",
    category: "intelligence",
    endpoint: "api.gdeltproject.org",
    interval: "10 min",
    requiresKey: false,
    status: "active",
    layerId: "news",
    recordType: "Geolocated articles",
    provider: "GDELT Project",
    docs: "https://blog.gdeltproject.org/gdelt-geo-2-0-api-searching-the-world/",
  },
  {
    id: "noaa-space-weather",
    name: "NOAA Space Weather",
    description: "Planetary Kp geomagnetic index. Monitors solar storms that can disrupt GPS, communications, and power grids.",
    category: "environment",
    endpoint: "services.swpc.noaa.gov",
    interval: "15 min",
    requiresKey: false,
    status: "active",
    layerId: "spaceWeather",
    recordType: "Kp index readings",
    provider: "NOAA SWPC",
    docs: "https://www.swpc.noaa.gov/products/planetary-k-index",
  },
  {
    id: "sc-hotspots",
    name: "SC Geopolitical Hotspots",
    description: "12 critical supply chain chokepoints and risk zones — Suez, Hormuz, Taiwan Strait, Panama Canal, and more.",
    category: "intelligence",
    endpoint: "local",
    interval: "Static",
    requiresKey: false,
    status: "active",
    layerId: "hotspots",
    recordType: "Hotspot markers",
    provider: "Curated",
  },

  // ── Requires API key ───────────────────────────
  {
    id: "aisstream-ships",
    name: "AISStream Ships",
    description: "Live vessel tracking via AIS WebSocket stream. Requires a free API key from AISStream.io.",
    category: "transport",
    endpoint: "stream.aisstream.io",
    interval: "Real-time (WS)",
    requiresKey: true,
    keyEnvVar: "VITE_AISSTREAM_API_KEY",
    status: "requires-key",
    layerId: "ships",
    recordType: "Vessel positions",
    provider: "AISStream.io",
    docs: "https://aisstream.io/documentation",
  },
  {
    id: "acled-conflicts",
    name: "ACLED Conflicts",
    description: "Armed conflict events, protests, and political violence. Requires free ACLED researcher access.",
    category: "intelligence",
    endpoint: "acleddata.com",
    interval: "1 hour",
    requiresKey: true,
    keyEnvVar: "VITE_ACLED_KEY",
    status: "requires-key",
    layerId: "conflicts",
    recordType: "Conflict events",
    provider: "ACLED",
    docs: "https://acleddata.com/acleddatanew/wp-content/uploads/2021/11/ACLED_API-User-Guide_2021.pdf",
  },

  // ── Available (could be added) ─────────────────
  {
    id: "alpha-vantage",
    name: "Alpha Vantage Commodities",
    description: "Commodity prices — crude oil, natural gas, copper, wheat. Free tier: 25 requests/day.",
    category: "economic",
    endpoint: "alphavantage.co",
    interval: "30 min",
    requiresKey: true,
    keyEnvVar: "VITE_ALPHA_VANTAGE_KEY",
    status: "requires-key",
    recordType: "Price data",
    provider: "Alpha Vantage",
    docs: "https://www.alphavantage.co/documentation/",
  },
  {
    id: "noaa-weather-radar",
    name: "NOAA Weather Radar",
    description: "Real-time weather radar imagery and severe weather warnings across the US.",
    category: "environment",
    endpoint: "api.weather.gov",
    interval: "5 min",
    requiresKey: false,
    status: "available",
    recordType: "Weather alerts",
    provider: "NOAA NWS",
    docs: "https://www.weather.gov/documentation/services-web-api",
  },
  {
    id: "sentinel-imagery",
    name: "Sentinel-2 Satellite Imagery",
    description: "High-resolution satellite imagery for crop monitoring, deforestation, and environmental change detection.",
    category: "environment",
    endpoint: "services.sentinel-hub.com",
    interval: "On demand",
    requiresKey: true,
    status: "available",
    recordType: "Satellite tiles",
    provider: "Copernicus / ESA",
  },
  {
    id: "un-comtrade",
    name: "UN Comtrade Trade Flows",
    description: "International trade flow data between countries. Tracks imports/exports by commodity and partner.",
    category: "economic",
    endpoint: "comtradeapi.un.org",
    interval: "Monthly",
    requiresKey: true,
    status: "available",
    recordType: "Trade records",
    provider: "United Nations",
    docs: "https://comtradeapi.un.org/",
  },
  {
    id: "world-bank-logistics",
    name: "World Bank LPI",
    description: "Logistics Performance Index — measures trade logistics efficiency across 160+ countries.",
    category: "economic",
    endpoint: "api.worldbank.org",
    interval: "Yearly",
    requiresKey: false,
    status: "available",
    recordType: "Country scores",
    provider: "World Bank",
  },
];

export const CATEGORIES = [
  { id: "natural", label: "Natural", color: "#ffcc22" },
  { id: "transport", label: "Transport", color: "#88ccff" },
  { id: "intelligence", label: "Intelligence", color: "#a06fff" },
  { id: "environment", label: "Environment", color: "#22dd88" },
  { id: "economic", label: "Economic", color: "#ff8844" },
] as const;
